config-version: 2

name: "air_boltic_data"
version: "3.0.0"
require-dbt-version: ">=1.5.0"

dbt-cloud:
  project-id: 123456

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Europe/Tallinn"

seeds:
  air_boltic:
    +schema: raw
    air-boltic-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  air_boltic:
    staging:
      +materialized: view
    marts:
      +materialized: table
